services:
  aic-hcmc-2024:
    container_name: ezai
    stop_grace_period: 1s
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - utils_cache:/utils

volumes:
  utils_cache: