import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@mui/material";
import { MuiTheme } from "@/mui/theme";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { MainContextProvider } from "@/contexts/main";
import { ToastProvider } from "@/components/common/Toast";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppRouterCacheProvider>
          <MainContextProvider>
            <ThemeProvider theme={MuiTheme}>
              <ToastProvider> {children}</ToastProvider>
            </ThemeProvider>
          </MainContextProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
